# Generated by Django 6.1 on 2026-09-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='completed',
            new_name='completada',
        ),
    ]
